### ISSUE TITLE
feat: header section

### ISSUE THREAD

**Issue by paiakarit** [cybermm/cybermm.github.io#2]
- According to the #1, the header section has been designed.

![header-section](https://user-images.githubusercontent.com/76231238/198917584-af3bd0fd-81ef-4063-895e-b4314d585cba.png)

**Comment by paiakarit** [comment]
- The issue has been reopened to develop header section.

> The responsibilities will be developed by the @cybermm/frontend team.

**Comment by paiakarit** [comment]
- The issue has been reopened to develop header section.

> The above responsibility will be developed by the @cybermm/frontend team.

**Comment by minkgkyaw** [comment]
now i take that section
